# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10

  - name: Formations
    weight: 20
    identifier: formations
  - name: Data science
    PageRef: formations/data-science/_index.md
    weight: 10
    parent: formations
  - name: Robotics
    PageRef: formations/robotics/_index.md
    weight: 20
    parent: formations

  - name: Courses
    weight: 30
    identifier: courses
  - name: Data science
    PageRef: course/data-science/_index.md
    weight: 10
    parent: courses
  - name: Robotics
    PageRef: course/robotics/_index.md
    weight: 20
    parent: courses

  - name: Coaching/Mentoring
    weight: 40
    identifier: coaching
  - name: Data science
    PageRef: coaching/data-science/_index.md
    weight: 10
    parent: coaching
  - name: Robotics
    PageRef: coaching/robotics/_index.md
    weight: 20
    parent: coaching

  - name: Blog
    PageRef: post/_index.md
    weight: 50
  - name: Contact
    PageRef: contact/index.md
    weight: 60
